// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Asou.Abstractions.Events.EventSubscriptionModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventSubscriptionType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProcessInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EventSubscriptionModel");
                });

            modelBuilder.Entity("Asou.Abstractions.Process.Execution.ProcessExecutionLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessContractId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessVersionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessExecutionLogModel");
                });

            modelBuilder.Entity("Asou.Abstractions.Process.Execution.ProcessParameterPersistentModel", b =>
                {
                    b.Property<Guid>("ProcessInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProcessInstanceId");

                    b.ToTable("ProcessParameterPersistentModel");
                });

            modelBuilder.Entity("Asou.Abstractions.Process.Instance.ProcessInstanceModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<byte>("PersistenceType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProcessContractId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProcessVersionId")
                        .HasColumnType("TEXT");

                    b.Property<byte>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProcessInstanceModel");
                });
#pragma warning restore 612, 618
        }
    }
}
